name: Install Python dependencies

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version"
        required: true
        type: string

jobs:
  install-dependencies:
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Install Python v${{ input.python-version }} dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '${{ input.python-version }}'
          cache: "pip"
        run: pip install -r requirements.txt
