name: Validate Python version, linting and type-checking

on: [pull_request, push]

runs-on: ${{ matrix.os }}
strategy:
  matrix:
    python-version: ['3.9', '3.12']
    os: [ubuntu-latest, windows-latest]

jobs:
  validate:
    steps:
      - name: Validate Python version ${{ matrix.python-version }} (vermin)
        uses: ./.github/workflows/install-dependencies.yaml
        with:
          python-version: '${{ matrix.python-version }}'
        run: vermin -t=${{ matrix.python-version }} --violations --eval-annotations --backport asyncio --backport configparser --backport typing

  type-check:
    steps:
      - name: Run mypy type-checking
        uses: ./.github/workflows/install-dependencies.yaml
        with:
          python-version: '${{ matrix.python-version }}'
        run: mypy src --config-file=setup.cfg --explicit-package-bases --ignore-missing-imports

  lint:
    steps:
      - uses: ./.github/workflows/install-dependencies.yaml
        with:
          python-version: '${{ matrix.python-version }}'

      - name: Run flake8 linting
        run: flake8 src

      - name: Run black linting
        run: black src --check --diff --color
